version: "2"
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - E:\AdbrewTest-master\src:/src

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - E:\AdbrewTest-master\src:/src

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - E:\AdbrewTest-master\src:/src
      - E:\AdbrewTest-master\db:/data/db
    command: mongod --bind_ip 0.0.0.0
